export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const RESET = 'RESET';
export const SET_ALL_WORDS = 'SET_ALL_WORDS';
export const SET_LOADING_STATUS = 'SET_LOADING_STATUS';

export const $GAME_CORRECT_ANSWER = 'GAME.CORRECT_ANSWER';