export const SET_ALL_WORDS = 'SET_ALL_WORDS';
export const SET_LOADING_STATUS = 'SET_LOADING_STATUS';
export const SET_ALL_CATEGORIES = 'SET_ALL_CATEGORIES';
export const GAME_CORRECT_ANSWER = 'GAME.CORRECT_ANSWER';
export const SET_SELECTED_CATEGORIES = 'SET_SELECTED_CATEGORIES'